Fix args to traceback.format_exception_only-py3.9
Issue- Some pytest cases fail on Python 3.9 with error message TypeError: format_exception_only() missing 1 required positional argument: 'value'

Fix-Use the Python 3.9 signature for traceback.format_exception_only().